# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Kevin Nguy
tagline:          'No More Hello World'
description:      'A simple blog'
url:              https://github.com/kevinnguy

author:
  name:           'Kevin Nguy'

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/kevinnguy
